name: GitHubActionsBuilds

on: push

jobs:
  generate_version_number:
    runs-on: ubuntu-latest
    outputs:
      build_number: ${{ steps.buildnumber.outputs.build_number }}
    steps:
    - name: Generate build number
      id: buildnumber
      uses: einaregilsson/build-number@v3 
      with:
        token: ${{secrets.github_token}}

  build_docker:
    needs: generate_version_number
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v1
      with:
        image: tonistiigi/binfmt:latest
        platforms: all
    - name: Available platforms
      run: echo ${{ steps.qemu.outputs.platforms }}
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
    - name: Builder instance name
      run: echo ${{ steps.buildx.outputs.name }}
    - name: Available platforms
      run: echo ${{ steps.buildx.outputs.platforms }}
    - name: Run Buildx
      run: |
        export VERSION=1.0.${{needs.generate_version_number.outputs.build_number}}
        echo Version: $VERSION
        docker buildx build -f DeveReproduceXmlSerializerBug.ConsoleApp/Dockerfile --build-arg BUILD_VERSION=$VERSION --platform linux/arm,linux/arm64,linux/amd64 -t devedse/devereproducexmlserializerbugconsoleapp:${{needs.generate_version_number.outputs.build_number}} -t devedse/devereproducexmlserializerbugconsoleapp:latest .

  
  build_linux_6_0_402:
    needs: generate_version_number
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.402
    - name: dotnet restore
      run: dotnet restore DeveReproduceXmlSerializerBug.sln
    - name: dotnet build
      run: dotnet build DeveReproduceXmlSerializerBug.sln -c Release --no-restore /p:Version=1.0.${{needs.generate_version_number.outputs.build_number}}
    - name: dotnet test
      run: dotnet test DeveReproduceXmlSerializerBug.sln -c Release --no-build --verbosity normal

  build_linux_6_0_403:
    needs: generate_version_number
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.403
    - name: dotnet restore
      run: dotnet restore DeveReproduceXmlSerializerBug.sln
    - name: dotnet build
      run: dotnet build DeveReproduceXmlSerializerBug.sln -c Release --no-restore /p:Version=1.0.${{needs.generate_version_number.outputs.build_number}}
    - name: dotnet test
      run: dotnet test DeveReproduceXmlSerializerBug.sln -c Release --no-build --verbosity normal

  build_linux_6_0_x:
    needs: generate_version_number
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: dotnet restore
      run: dotnet restore DeveReproduceXmlSerializerBug.sln
    - name: dotnet build
      run: dotnet build DeveReproduceXmlSerializerBug.sln -c Release --no-restore /p:Version=1.0.${{needs.generate_version_number.outputs.build_number}}
    - name: dotnet test
      run: dotnet test DeveReproduceXmlSerializerBug.sln -c Release --no-build --verbosity normal

  build_windows_6_0_402:
    needs: generate_version_number
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.402
    - name: dotnet restore
      run: dotnet restore DeveReproduceXmlSerializerBug.sln
    - name: dotnet build
      run: dotnet build DeveReproduceXmlSerializerBug.sln -c Release --no-restore /p:Version=1.0.${{needs.generate_version_number.outputs.build_number}}
    - name: dotnet test
      run: dotnet test DeveReproduceXmlSerializerBug.sln -c Release --no-build --verbosity normal

  build_windows_6_0_403:
    needs: generate_version_number
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.403
    - name: dotnet restore
      run: dotnet restore DeveReproduceXmlSerializerBug.sln
    - name: dotnet build
      run: dotnet build DeveReproduceXmlSerializerBug.sln -c Release --no-restore /p:Version=1.0.${{needs.generate_version_number.outputs.build_number}}
    - name: dotnet test
      run: dotnet test DeveReproduceXmlSerializerBug.sln -c Release --no-build --verbosity normal

  build_windows_6_0_x:
    needs: generate_version_number
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: dotnet restore
      run: dotnet restore DeveReproduceXmlSerializerBug.sln
    - name: dotnet build
      run: dotnet build DeveReproduceXmlSerializerBug.sln -c Release --no-restore /p:Version=1.0.${{needs.generate_version_number.outputs.build_number}}
    - name: dotnet test
      run: dotnet test DeveReproduceXmlSerializerBug.sln -c Release --no-build --verbosity normal